function function (name) {
  return this._name;
}(locals) {
var jade_debug = [{ lineno: 1, filename: "/home/reed/Documents/school/cs360/broadcasts/views/error.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (error, message, title) {
jade_debug.unshift({ lineno: 0, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.unshift({ lineno: 1, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<html ng-app=\"broadcastsApp\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<head>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<title>" + (jade.escape(null == (jade_interp = title) ? "" : jade_interp)));
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<link rel=\"stylesheet\" href=\"/stylesheets/style.css\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<script src=\"/javascripts/angular.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular-route.min.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<script src=\"/javascripts/controllers.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<body>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.unshift({ lineno: 4, filename: "/home/reed/Documents/school/cs360/broadcasts/views/error.jade" });
buf.push("<h1>" + (jade.escape(null == (jade_interp = message) ? "" : jade_interp)));
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</h1>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "/home/reed/Documents/school/cs360/broadcasts/views/error.jade" });
buf.push("<h2>" + (jade.escape(null == (jade_interp = error.status) ? "" : jade_interp)));
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</h2>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "/home/reed/Documents/school/cs360/broadcasts/views/error.jade" });
buf.push("<pre>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("" + (jade.escape((jade_interp = error.stack) == null ? '' : jade_interp)) + "");
jade_debug.shift();
jade_debug.shift();
buf.push("</pre>");
jade_debug.shift();
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<!-- Latest compiled and minified CSS-->");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.shift();}.call(this,"error" in locals_for_with?locals_for_with.error:typeof error!=="undefined"?error:undefined,"message" in locals_for_with?locals_for_with.message:typeof message!=="undefined"?message:undefined,"title" in locals_for_with?locals_for_with.title:typeof title!=="undefined"?title:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "extends layout\n\nblock content\n  h1= message\n  h2= error.status\n  pre #{error.stack}\n");
}
}