function function (name) {
  return this._name;
}(locals) {
var jade_debug = [{ lineno: 1, filename: "/home/reed/Documents/school/cs360/broadcasts/views/login.jade" }];
try {
var buf = [];
var jade_mixins = {};
var jade_interp;
;var locals_for_with = (locals || {});(function (title) {
jade_debug.unshift({ lineno: 0, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.unshift({ lineno: 1, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<!DOCTYPE html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 2, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<html ng-app=\"broadcastsApp\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<head>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<title>" + (jade.escape(null == (jade_interp = title) ? "" : jade_interp)));
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</title>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<link rel=\"stylesheet\" href=\"/stylesheets/style.css\">");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<script src=\"/javascripts/angular.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 8, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.2.0rc1/angular-route.min.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.unshift({ lineno: 9, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<script src=\"/javascripts/controllers.js\">");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.shift();
buf.push("</script>");
jade_debug.shift();
jade_debug.shift();
buf.push("</head>");
jade_debug.shift();
jade_debug.unshift({ lineno: 10, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<body>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 3, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.unshift({ lineno: 4, filename: "/home/reed/Documents/school/cs360/broadcasts/views/login.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 4, filename: jade_debug[0].filename });
buf.push("Sign in with Google");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 5, filename: "/home/reed/Documents/school/cs360/broadcasts/views/login.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 5, filename: jade_debug[0].filename });
buf.push("Sign in with Twitter");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 6, filename: "/home/reed/Documents/school/cs360/broadcasts/views/login.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 6, filename: jade_debug[0].filename });
buf.push("Sign in with Facebook");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.unshift({ lineno: 7, filename: "/home/reed/Documents/school/cs360/broadcasts/views/login.jade" });
buf.push("<p>");
jade_debug.unshift({ lineno: undefined, filename: jade_debug[0].filename });
jade_debug.unshift({ lineno: 7, filename: jade_debug[0].filename });
buf.push("Sign in with Github");
jade_debug.shift();
jade_debug.shift();
buf.push("</p>");
jade_debug.shift();
jade_debug.shift();
jade_debug.shift();
buf.push("</body>");
jade_debug.shift();
jade_debug.shift();
buf.push("</html>");
jade_debug.shift();
jade_debug.unshift({ lineno: 14, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("<!-- Latest compiled and minified CSS-->");
jade_debug.shift();
jade_debug.unshift({ lineno: 15, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 16, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 17, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 18, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 19, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
buf.push("");
jade_debug.shift();
jade_debug.unshift({ lineno: 20, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.unshift({ lineno: 21, filename: "/home/reed/Documents/school/cs360/broadcasts/views/layout.jade" });
jade_debug.shift();
jade_debug.shift();}.call(this,"title" in locals_for_with?locals_for_with.title:typeof title!=="undefined"?title:undefined));;return buf.join("");
} catch (err) {
  jade.rethrow(err, jade_debug[0].filename, jade_debug[0].lineno, "extends layout\n\nblock content\n  p Sign in with Google\n  p Sign in with Twitter\n  p Sign in with Facebook\n  p Sign in with Github\n");
}
}